import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  organizations: defineTable({ name: v.string(), slug: v.string(), createdBy: v.string(), createdAt: v.number() }).index("by_slug", ["slug"]),
  memberships: defineTable({ organizationId: v.id("organizations"), userId: v.string(), role: v.union(v.literal("owner"), v.literal("reviewer"), v.literal("member")) }).index("by_org_user", ["organizationId", "userId"]),
  startupProfiles: defineTable({ organizationId: v.id("organizations"), organizationType: v.union(v.literal("startup"), v.literal("institution")), name: v.string(), website: v.string(), location: v.string(), region: v.string(), stage: v.string(), sectors: v.array(v.string()), raiseAmountUsd: v.number(), oneLiner: v.string(), traction: v.string(), impact: v.string(), founderContext: v.string(), targetRegions: v.array(v.string()), status: v.union(v.literal("draft"), v.literal("active"), v.literal("archived")), consentRecordedAt: v.number(), updatedAt: v.number() }).index("by_organization", ["organizationId"]),
  sources: defineTable({ organizationId: v.id("organizations"), url: v.string(), title: v.optional(v.string()), provider: v.union(v.literal("exa"), v.literal("manual")), providerRequestId: v.optional(v.string()), capturedAt: v.number(), excerpt: v.optional(v.string()), contentHash: v.optional(v.string()) }).index("by_url", ["url"]),
  investors: defineTable({ organizationId: v.id("organizations"), firm: v.string(), person: v.optional(v.string()), role: v.optional(v.string()), region: v.string(), website: v.string(), email: v.optional(v.string()), contactType: v.union(v.literal("generic_business"), v.literal("named_business"), v.literal("unknown")), thesis: v.string(), stages: v.array(v.string()), sectors: v.array(v.string()), geographies: v.array(v.string()), sourceIds: v.array(v.id("sources")), lastVerifiedAt: v.number() }).index("by_org_firm", ["organizationId", "firm"]),
  campaigns: defineTable({ organizationId: v.id("organizations"), startupProfileId: v.id("startupProfiles"), name: v.string(), status: v.union(v.literal("draft"), v.literal("review"), v.literal("approved"), v.literal("running"), v.literal("paused"), v.literal("complete")), dailyLimit: v.number(), createdBy: v.string(), createdAt: v.number() }).index("by_organization", ["organizationId"]),
  matches: defineTable({ campaignId: v.id("campaigns"), investorId: v.id("investors"), score: v.number(), reasons: v.array(v.string()), risks: v.array(v.string()), model: v.optional(v.string()), promptVersion: v.optional(v.string()), createdAt: v.number() }).index("by_campaign_score", ["campaignId", "score"]),
  catalogueListings: defineTable({ organizationId: v.id("organizations"), startupProfileId: v.id("startupProfiles"), visibility: v.union(v.literal("private"), v.literal("review"), v.literal("listed")), publicContext: v.string(), publicStrengths: v.array(v.string()), publicConsiderations: v.array(v.string()), publicTraction: v.string(), approvedBy: v.optional(v.string()), approvedAt: v.optional(v.number()), updatedAt: v.number() }).index("by_visibility", ["visibility"]).index("by_organization", ["organizationId"]),
  investorInterests: defineTable({ listingId: v.id("catalogueListings"), investorOrganizationId: v.id("organizations"), investorUserId: v.string(), note: v.optional(v.string()), status: v.union(v.literal("submitted"), v.literal("shared"), v.literal("accepted"), v.literal("declined")), createdAt: v.number() }).index("by_listing", ["listingId"]).index("by_investor", ["investorOrganizationId"]),
  messages: defineTable({ campaignId: v.id("campaigns"), investorId: v.id("investors"), subject: v.string(), body: v.string(), status: v.union(v.literal("draft"), v.literal("approved"), v.literal("queued"), v.literal("sent"), v.literal("failed"), v.literal("suppressed")), approvedBy: v.optional(v.string()), approvedAt: v.optional(v.number()), providerMessageId: v.optional(v.string()), idempotencyKey: v.string(), createdAt: v.number() }).index("by_campaign", ["campaignId"]).index("by_idempotency", ["idempotencyKey"]),
  suppressions: defineTable({ emailHash: v.string(), reason: v.union(v.literal("unsubscribe"), v.literal("bounce"), v.literal("complaint"), v.literal("manual")), createdAt: v.number(), source: v.string() }).index("by_email_hash", ["emailHash"]),
  webhookEvents: defineTable({ provider: v.string(), eventId: v.string(), type: v.string(), payload: v.any(), receivedAt: v.number() }).index("by_provider_event", ["provider", "eventId"]),
  auditEvents: defineTable({ organizationId: v.id("organizations"), actorId: v.string(), action: v.string(), entityType: v.string(), entityId: v.string(), metadata: v.optional(v.any()), createdAt: v.number() }).index("by_organization_time", ["organizationId", "createdAt"]),
});
